apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: echo
spec:
  environments:
    - name: prod
      build:
        from: master
    - name: dev
      build:
        from: develop
  components:
    - name: www
      src: ./www
      ports:
       - name: http
         port: 3001
      public: true
      monitoring: false
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"
      replicas: 1
      environmentVariables:
        - environment: prod
          variables:
            PORT: 3001
            NODE_ENV: "production"
            ECHO_URL: "http://echo:3000"
        - environment: dev
          variables:
            PORT: 3001
            NODE_ENV: "development"
            ECHO_URL: "http://echo:3000"
    - name: echo
      src: ./echo
      ports:
      - name: http
        port: 3000
      public: false
      monitoring: false
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"
      replicas: 2
      environmentVariables:
        - environment: prod
          variables:
            PORT: 3000
            NODE_ENV: "production"
        - environment: dev
          variables:
            PORT: 3000
            NODE_ENV: "development"